import { EventSchema, GA4Event, GA4Parameter } from '../generator/event-schema';

export interface SchemaDiffChange {
  eventName: string;
  before: GA4Event;
  after: GA4Event;
}

export interface SchemaDiffResult {
  added: GA4Event[];
  removed: GA4Event[];
  changed: SchemaDiffChange[];
  unchanged: GA4Event[];
}

function stableStringify(value: unknown): string {
  if (value === null || typeof value !== 'object') {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(item => stableStringify(item)).join(',')}]`;
  }
  const entries = Object.entries(value as Record<string, unknown>)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, item]) => `${JSON.stringify(key)}:${stableStringify(item)}`);
  return `{${entries.join(',')}}`;
}

function normalizeParameters(parameters: GA4Parameter[]): GA4Parameter[] {
  return [...parameters].sort((left, right) => left.name.localeCompare(right.name));
}

function normalizeEvent(event: GA4Event): GA4Event {
  return {
    ...event,
    parameters: normalizeParameters(event.parameters),
  };
}

function eventEquals(left: GA4Event, right: GA4Event): boolean {
  return stableStringify(normalizeEvent(left)) === stableStringify(normalizeEvent(right));
}

export function diffEventSchemas(current: EventSchema, baseline: EventSchema): SchemaDiffResult {
  const currentMap = new Map(current.events.map(event => [event.eventName, event]));
  const baselineMap = new Map(baseline.events.map(event => [event.eventName, event]));

  const added: GA4Event[] = [];
  const removed: GA4Event[] = [];
  const changed: SchemaDiffChange[] = [];
  const unchanged: GA4Event[] = [];

  for (const [eventName, event] of currentMap.entries()) {
    const before = baselineMap.get(eventName);
    if (!before) {
      added.push(event);
      continue;
    }
    if (eventEquals(event, before)) {
      unchanged.push(event);
      continue;
    }
    changed.push({
      eventName,
      before,
      after: event,
    });
  }

  for (const [eventName, event] of baselineMap.entries()) {
    if (!currentMap.has(eventName)) {
      removed.push(event);
    }
  }

  return {
    added: added.sort((left, right) => left.eventName.localeCompare(right.eventName)),
    removed: removed.sort((left, right) => left.eventName.localeCompare(right.eventName)),
    changed: changed.sort((left, right) => left.eventName.localeCompare(right.eventName)),
    unchanged: unchanged.sort((left, right) => left.eventName.localeCompare(right.eventName)),
  };
}

function renderEventList(events: GA4Event[]): string {
  if (events.length === 0) return '- none';
  return events.map(event => `- \`${event.eventName}\` (${event.triggerType}, ${event.priority})`).join('\n');
}

function renderChangedEventList(changes: SchemaDiffChange[]): string {
  if (changes.length === 0) return '- none';
  return changes.map(change =>
    `- \`${change.eventName}\`: ${change.before.triggerType}/${change.before.priority} -> ${change.after.triggerType}/${change.after.priority}`,
  ).join('\n');
}

export function generateSchemaDiffReportMarkdown(args: {
  current: EventSchema;
  baseline: EventSchema;
  diff: SchemaDiffResult;
  title?: string;
}): string {
  const { current, baseline, diff } = args;
  const title = args.title || 'Event Schema Diff Report';

  const lines: string[] = [
    `# ${title}`,
    '',
    `**Current schema generated at:** ${new Date(current.generatedAt).toLocaleString()}`,
    `**Baseline schema generated at:** ${new Date(baseline.generatedAt).toLocaleString()}`,
    `**Current events:** ${current.events.length}`,
    `**Baseline events:** ${baseline.events.length}`,
    '',
    '## Summary',
    '',
    '| Metric | Count |',
    '| --- | ---: |',
    `| Added | ${diff.added.length} |`,
    `| Removed | ${diff.removed.length} |`,
    `| Changed | ${diff.changed.length} |`,
    `| Unchanged | ${diff.unchanged.length} |`,
    '',
    '## Added Events',
    '',
    renderEventList(diff.added),
    '',
    '## Removed Events',
    '',
    renderEventList(diff.removed),
    '',
    '## Changed Events',
    '',
    renderChangedEventList(diff.changed),
    '',
    '_Generated by analytics-tracking-automation_',
  ];

  return lines.join('\n');
}

export function generateBusinessChangeSummaryMarkdown(args: {
  diff: SchemaDiffResult;
  title?: string;
}): string {
  const { diff } = args;
  const title = args.title || 'Tracking Change Summary';

  const changeLevel =
    diff.removed.length > 0
      ? 'high'
      : (diff.changed.length > 0 || diff.added.length > 0 ? 'medium' : 'low');

  const lines: string[] = [
    `# ${title}`,
    '',
    `**Change intensity:** ${changeLevel}`,
    '',
    '## What Changed',
    '',
    `- Added events: ${diff.added.length}`,
    `- Edited events: ${diff.changed.length}`,
    `- Removed events: ${diff.removed.length}`,
    '',
    '## Business Impact',
    '',
    diff.added.length > 0
      ? `- New tracking coverage was introduced for ${diff.added.length} user journey point(s).`
      : '- No new tracking coverage was introduced.',
    diff.changed.length > 0
      ? `- Existing data definitions changed for ${diff.changed.length} event(s), so dashboards may need verification.`
      : '- Existing event definitions were not changed.',
    diff.removed.length > 0
      ? `- ${diff.removed.length} event(s) were removed; dependent reports and alerts should be reviewed.`
      : '- No events were removed.',
    '',
    '## Recommended Follow-up',
    '',
    '- Re-run GTM generation and preview verification before publish.',
    '- Notify analytics/reporting owners to validate affected dashboards.',
    '',
    '_Generated by analytics-tracking-automation_',
  ];

  return lines.join('\n');
}
