import * as fs from 'fs';
import * as path from 'path';

import { TrackingHealthReport, formatTrackingHealthScore } from './tracking-health';

export const TRACKING_HEALTH_REPORT_FILE = 'tracking-health-report.md';

function gradeLabel(grade: TrackingHealthReport['grade']): string {
  if (grade === 'good') return 'Good';
  if (grade === 'warning') return 'Warning';
  if (grade === 'critical') return 'Critical';
  return 'Manual Required';
}

function bulletList(lines: string[]): string[] {
  if (lines.length === 0) return ['- none'];
  return lines.map(line => `- ${line}`);
}

export function generateTrackingHealthReportMarkdown(report: TrackingHealthReport): string {
  const lines: string[] = [
    '# Tracking Health Report',
    '',
    `**Generated:** ${new Date(report.generatedAt).toLocaleString()}`,
    `**Site:** ${report.siteUrl}`,
    `**Container:** ${report.gtmContainerId}`,
    `**Mode:** ${report.mode}`,
    '',
    '## Health Summary',
    '',
    '| Metric | Value |',
    '| --- | --- |',
    `| Score | ${formatTrackingHealthScore(report.score)} |`,
    `| Grade | ${gradeLabel(report.grade)} |`,
    `| Total schema events | ${report.totalSchemaEvents} |`,
    `| Expected in preview | ${report.totalExpected} |`,
    `| Fired | ${report.totalFired} |`,
    `| Failed | ${report.totalFailed} |`,
    `| Unexpected events | ${report.unexpectedFiredCount} |`,
    '',
    '## Blockers',
    '',
    ...bulletList(report.blockers),
    '',
    '## Recommendations',
    '',
    ...bulletList(report.recommendations),
    '',
    '## Event Status',
    '',
    '| Event | Priority | Fired | Failure Category |',
    '| --- | --- | --- | --- |',
    ...(report.eventStatus.length > 0
      ? report.eventStatus.map(event =>
        `| \`${event.eventName}\` | ${event.priority} | ${event.fired ? 'yes' : 'no'} | ${event.failureCategory || '—'} |`)
      : ['| _none_ | — | — | — |']),
    '',
  ];

  if (report.baseline) {
    const baselineDelta = typeof report.baseline.scoreDelta === 'number'
      ? (report.baseline.scoreDelta >= 0 ? `+${report.baseline.scoreDelta}` : `${report.baseline.scoreDelta}`)
      : 'n/a';
    lines.push(
      '## Baseline Comparison',
      '',
      '| Metric | Value |',
      '| --- | --- |',
      `| Baseline file | ${report.baseline.file || 'previous tracking-health.json'} |`,
      `| Previous score | ${formatTrackingHealthScore(report.baseline.previousScore)} |`,
      `| Score delta | ${baselineDelta} |`,
      '',
      '**Fixed events**',
      '',
      ...bulletList(report.baseline.fixedEvents),
      '',
      '**New failures**',
      '',
      ...bulletList(report.baseline.newFailures),
      '',
    );
  }

  if (report.unexpectedEventNames.length > 0) {
    lines.push(
      '## Unexpected Fired Events',
      '',
      ...report.unexpectedEventNames.map(name => `- \`${name}\``),
      '',
    );
  }

  lines.push('_Generated by analytics-tracking-automation_');
  return lines.join('\n');
}

export function writeTrackingHealthReportMarkdown(file: string, report: TrackingHealthReport): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${generateTrackingHealthReportMarkdown(report)}\n`);
}
